name: kgmulqa
channels:
  - defaults
dependencies:
  - pip=24.2
  - python=3.10
  - pip:
    - beautifulsoup4==4.13.1
    - faiss-cpu==1.13.2
    - faiss-gpu==1.7.2
    - huggingface-hub==0.28.1
    - langchain==0.3.17
    - langchain-anthropic==0.3.7
    - langchain-community==0.3.16
    - langchain-google-genai==2.0.9
    - langchain-openai==0.3.3
    - Levenshtein==0.26.1
    - openllm==0.6.17
    - pandas==2.2.3
    - rdflib==7.1.3
    - sentence-transformers==5.2.0
    - scikit-learn==1.6.1
    - vllm==0.7.1
